spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging:
  level:
    root: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    org.apache.coyote.http11: DEBUG
    your.package.name: TRACE


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

logging:
  level:
    root: TRACE
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    org.apache.coyote.http11: DEBUG
    your.package.name: TRACE


